apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: student03
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: image-registry.openshift-image-registry.svc:5000/devops/code-server-student:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: STUDENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: workspace-volume
              mountPath: /home/coder/workspace
          securityContext:
            runAsUser: 1001
            runAsGroup: 0
            allowPrivilegeEscalation: false
            runAsNonRoot: true
      volumes:
        - name: workspace-volume
          emptyDir: {}  # You can replace with persistentVolumeClaim if needed
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: student03
spec:
  selector:
    app: code-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: code-server
  namespace: student03
spec:
  to:
    kind: Service
    name: code-server
  port:
    targetPort: 8080
  tls:
    termination: edge
