apiVersion: v1
kind: ResourceQuota
metadata:
  name: student-quota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    persistentvolumeclaims: "3"
    requests.storage: 10Gi
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
