# ==============================================================================
# ArgoCD RBAC Configuration for Student Access
# Allows students to login with OpenShift credentials and see their applications
# ==============================================================================

# This configures ArgoCD to:
# 1. Allow OpenShift SSO login for students (student01, student02, etc.)
# 2. Give students permission to view their own applications only
# 3. Restrict access to applications in their own namespace

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy for authenticated users
  policy.default: role:readonly
  
  # RBAC policy definitions
  policy.csv: |
    # ===========================================================================
    # Student Access Policies
    # ===========================================================================
    
    # Define student role with restricted permissions
    p, role:student, applications, get, */*, allow
    p, role:student, applications, sync, */*, allow
    p, role:student, repositories, get, *, allow
    p, role:student, clusters, get, *, allow
    p, role:student, certificates, get, *, allow
    
    # Restrict students to only their own applications
    # Pattern: java-webapp-{student-id} applications
    p, role:student, applications, *, */java-webapp-*, allow
    
    # ===========================================================================
    # OpenShift User to Role Mappings
    # Map OpenShift users (student01, student02, etc.) to student role
    # ===========================================================================
    
    # Student01
    g, student01, role:student
    g, system:serviceaccount:student01:default, role:student
    
    # Student02  
    g, student02, role:student
    g, system:serviceaccount:student02:default, role:student
    
    # Student03
    g, student03, role:student
    g, system:serviceaccount:student03:default, role:student
    
    # Student04
    g, student04, role:student
    g, system:serviceaccount:student04:default, role:student
    
    # Student05
    g, student05, role:student
    g, system:serviceaccount:student05:default, role:student
    
    # Student06
    g, student06, role:student
    g, system:serviceaccount:student06:default, role:student
    
    # Student07
    g, student07, role:student
    g, system:serviceaccount:student07:default, role:student
    
    # Student08
    g, student08, role:student
    g, system:serviceaccount:student08:default, role:student
    
    # Student09
    g, student09, role:student
    g, system:serviceaccount:student09:default, role:student
    
    # Student10
    g, student10, role:student
    g, system:serviceaccount:student10:default, role:student
    
    # Student11
    g, student11, role:student
    g, system:serviceaccount:student11:default, role:student
    
    # Student12
    g, student12, role:student
    g, system:serviceaccount:student12:default, role:student
    
    # Student13
    g, student13, role:student
    g, system:serviceaccount:student13:default, role:student
    
    # Student14
    g, student14, role:student
    g, system:serviceaccount:student14:default, role:student
    
    # Student15
    g, student15, role:student
    g, system:serviceaccount:student15:default, role:student
    
    # Student16
    g, student16, role:student
    g, system:serviceaccount:student16:default, role:student
    
    # Student17
    g, student17, role:student
    g, system:serviceaccount:student17:default, role:student
    
    # Student18
    g, student18, role:student
    g, system:serviceaccount:student18:default, role:student
    
    # Student19
    g, student19, role:student
    g, system:serviceaccount:student19:default, role:student
    
    # Student20
    g, student20, role:student
    g, system:serviceaccount:student20:default, role:student
    
    # ===========================================================================
    # Admin Users (Instructors)
    # ===========================================================================
    
    # Instructor access - full admin
    g, instructor, role:admin
    g, admin, role:admin
    
    # ===========================================================================
    # Application-Specific Permissions
    # Fine-grained control: students can only see applications matching their ID
    # ===========================================================================
    
    # Student01 can only see java-webapp-student01
    p, student01, applications, *, default/java-webapp-student01, allow
    p, student01, applications, *, openshift-gitops/java-webapp-student01, allow
    
    # Student02 can only see java-webapp-student02  
    p, student02, applications, *, default/java-webapp-student02, allow
    p, student02, applications, *, openshift-gitops/java-webapp-student02, allow
    
    # Student03 can only see java-webapp-student03
    p, student03, applications, *, default/java-webapp-student03, allow
    p, student03, applications, *, openshift-gitops/java-webapp-student03, allow
    
    # Student04 can only see java-webapp-student04
    p, student04, applications, *, default/java-webapp-student04, allow
    p, student04, applications, *, openshift-gitops/java-webapp-student04, allow
    
    # Student05 can only see java-webapp-student05
    p, student05, applications, *, default/java-webapp-student05, allow
    p, student05, applications, *, openshift-gitops/java-webapp-student05, allow
    
    # Continue pattern for remaining students...
    # (Adding all 20 students for completeness)
    
    p, student06, applications, *, default/java-webapp-student06, allow
    p, student06, applications, *, openshift-gitops/java-webapp-student06, allow
    p, student07, applications, *, default/java-webapp-student07, allow  
    p, student07, applications, *, openshift-gitops/java-webapp-student07, allow
    p, student08, applications, *, default/java-webapp-student08, allow
    p, student08, applications, *, openshift-gitops/java-webapp-student08, allow
    p, student09, applications, *, default/java-webapp-student09, allow
    p, student09, applications, *, openshift-gitops/java-webapp-student09, allow
    p, student10, applications, *, default/java-webapp-student10, allow
    p, student10, applications, *, openshift-gitops/java-webapp-student10, allow
    p, student11, applications, *, default/java-webapp-student11, allow
    p, student11, applications, *, openshift-gitops/java-webapp-student11, allow
    p, student12, applications, *, default/java-webapp-student12, allow
    p, student12, applications, *, openshift-gitops/java-webapp-student12, allow
    p, student13, applications, *, default/java-webapp-student13, allow
    p, student13, applications, *, openshift-gitops/java-webapp-student13, allow
    p, student14, applications, *, default/java-webapp-student14, allow
    p, student14, applications, *, openshift-gitops/java-webapp-student14, allow
    p, student15, applications, *, default/java-webapp-student15, allow
    p, student15, applications, *, openshift-gitops/java-webapp-student15, allow
    p, student16, applications, *, default/java-webapp-student16, allow
    p, student16, applications, *, openshift-gitops/java-webapp-student16, allow
    p, student17, applications, *, default/java-webapp-student17, allow
    p, student17, applications, *, openshift-gitops/java-webapp-student17, allow
    p, student18, applications, *, default/java-webapp-student18, allow
    p, student18, applications, *, openshift-gitops/java-webapp-student18, allow
    p, student19, applications, *, default/java-webapp-student19, allow
    p, student19, applications, *, openshift-gitops/java-webapp-student19, allow
    p, student20, applications, *, default/java-webapp-student20, allow
    p, student20, applications, *, openshift-gitops/java-webapp-student20, allow

---

# ==============================================================================
# ArgoCD Server Configuration - Enable OpenShift OAuth
# ==============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # Enable OpenShift OAuth integration
  server.insecure: "false"
  oidc.config: |
    name: OpenShift
    issuer: https://kubernetes.default.svc
    clientId: system:serviceaccount:openshift-gitops:argocd-server
    clientSecret: $oidc.openshift.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}

---

# ==============================================================================  
# OpenShift OAuth Client for ArgoCD
# ==============================================================================
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: argocd-server
grantMethod: auto
redirectURIs:
- https://openshift-gitops-server-openshift-gitops.apps.bootcamp-ocs-cluster.bootcamp.tkmind.net/auth/callback
secret: argocd-server-secret

---

# ==============================================================================
# Service Account Token Secret for ArgoCD OAuth
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: argocd-server-oauth-secret
  namespace: openshift-gitops
  annotations:
    kubernetes.io/service-account.name: argocd-server
type: kubernetes.io/service-account-token
