apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-workshop-infrastructure
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/kevin-biot/code-server-student-image
    targetRevision: main
    path: infrastructure/manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-workshop
  namespace: openshift-gitops
spec:
  description: DevOps Workshop Infrastructure
  sourceRepos:
  - https://github.com/kevin-biot/code-server-student-image
  destinations:
  - namespace: 'devops-*'
    server: https://kubernetes.default.svc
  - namespace: 'student*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: tekton.dev
    kind: ClusterTask
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
